### ISSUE TITLE
catch templates that have templates inside them

### ISSUE THREAD

**Issue by jonathanbratt** [macmillancontentscience/wikimorphemes#29]
For example, from "argument":
```
{{suffix|en|argue|ment|pos2=suffix forming {{glossary|noun}}s from {{glossary|verb}}s, with the sense of ‘the action or result of what is denoted by the verb’}}
```

**Comment by jonathanbratt** [comment]
This is probably not something we should catch. If it happens, it should be fixed in wiktionary.

**Comment by jonthegeek** [comment]
Turns out this happens more often than we first thought. Reopening to investigate further, but right now we don't know of a case where this is a legitimate issue.
